version: "3"

services:
  collection.dungeon.studio:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - COLLECTION_SERVER_PORT=80
    image: dungeon-studio/collection.dungeon.studio:latest
    networks:
      - dungeon-studio
    ports:
      - "80"

networks:
  dungeon-studio:
